### ISSUE TITLE
Use markdown add content in the background how to do

### ISSUE THREAD

**Issue by yccphp** [KaneCohen/laravel-markdown#3]
Use markdown add content in the background how to do？

**Comment by KaneCohen** [comment]
@yccphp hey, can you elaborate? I'm not quite understand what you mean.

**Comment by yccphp** [comment]
Sorry, I am a Chinese, my English is poor, I say: When can add articles in the background, showing the markdown editor, and in this example the same. http://lab.lepture.com/editor/, and now I have achieved

**Comment by KaneCohen** [comment]
OK, still didn't quite get what you mean, but I assume you've found solution?

**Comment by yccphp** [comment]
Yes, I have found a solution, thank you

**Comment by KaneCohen** [comment]
@yccphp, awesome. Good luck!

**Comment by yccphp** [comment]
Thank you for your patience，Good luck!
